notepad/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notes.urls', namespace='notes'))
]

notes/urls.py
from django.urls import path
from notes import views

app_name = 'notes'

urlpatterns = [
    path('', views.NoteList.as_view(), name='notes'),
    path('create/', views.NoteCreate.as_view(), name='create'),
    path('notes/<slug:slug>/', views.NoteDetail.as_view(), name='detail'),
    path('notes/<slug:slug>/update/', views.NoteUpdate.as_view(), name='update'),
    path('notes/<slug:slug>/delete/', views.NoteDelete.as_view(), name='delete'),
]

notes/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.shortcuts import reverse, redirect
from django.utils.text import slugify

# Create your models here.
User = get_user_model()

class Note(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    slug = models.SlugField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('notes:detail', kwargs={'slug':self.slug})

    def save(self, *args, **kwargs):
        if not self.id:
            # newly created object, set slug
            self.slug = slugify(self.title)

        super(Note, self).save(*args, **kwargs)


    

notes/forms.py
from django import forms
from .models import Note

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'body',]

notes/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Note
from .forms import NoteForm

# Create your views here.
class NoteList(ListView):
    model = Note
    context_object_name = 'notes'
    template_name = 'index.html'


class NoteDetail(DetailView):
    queryset = Note.objects.all()
    context_object_name = 'note'
    template_name = 'detail.html'


class NoteCreate(CreateView):
    model = Note
    fields = ['title', 'body']
    template_name = 'create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Create'
        return context


class NoteUpdate(UpdateView):
    model = Note
    fields = ['title', 'body']
    template_name = 'create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edit'
        return context


class NoteDelete(DeleteView):
    model = Note
    success_url = reverse_lazy('notes:notes')
    template_name = 'confirm_delete_note.html'

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Notes{% block title %}{% endblock title %}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>
<body>
    <div class="container">
    <nav class="navbar" role="navigation" aria-label="main navigation">
      
        <div class="navbar-brand">
          <a class="navbar-item" href="https://bulma.io">
            <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
          </a>
      
          <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
      
        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start">
            <a class="navbar-item">
              Notes
            </a>
      
            <a href="{% url 'notes:create' %}" class="navbar-item">
              Create
            </a>
      
            
          </div>
      
          
        </div>
      </nav>
    </div>
      <main>
        <section class="section">
          <div class="container">
              {% block content %}
  {% endblock content %}
          </div>
        </section>
      </main>


  <footer class="footer">
    <div class="content has-text-centered">
      <p>
        The source code is created using 
        <a href="https://bulma.io/">Bulma</a> & <a href="https://www.djangoproject.com/">Django</a>.
      </p>
    </div>
  </footer>

  <script>
  
  document.addEventListener('DOMContentLoaded', () => {

// Get all "navbar-burger" elements
const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

// Check if there are any navbar burgers
if ($navbarBurgers.length > 0) {

  // Add a click event on each of them
  $navbarBurgers.forEach( el => {
    el.addEventListener('click', () => {

      // Get the target from the "data-target" attribute
      const target = el.dataset.target;
      const $target = document.getElementById(target);

      // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
      el.classList.toggle('is-active');
      $target.classList.toggle('is-active');

    });
  });
}

});
  
  </script>

</body>
</html>

templates/confirm_delete_note.html
{% extends 'base.html' %}

{% block title %} - Delete{% endblock title %}

{% block content %}

<h3 class="title is-3">Delete {{ note }}?</h3>

<form action="." method="post">
  {% csrf_token %}
  <div class="field is-grouped">
      <div class="control">
        <button type="submit" class="button is-danger">Delete</button>
      </div>
      <div class="control">
        <a href="{% url 'notes:notes' %}" class="button is-link is-light">Cancel</a>
      </div>
    </div>
</form>


{% endblock content %}

templates/create.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %} - {{title}}{% endblock title %}

{% block content %}
<h1 class="title">{{title}} Note</h1>
<div class="columns">
  <div class="column is-half">

    <form action="." method="post">
      {% csrf_token %}
    
      {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
      {% endfor %}
    
      {% if form.non_field_errors %}
    
      <div class="notification is-danger is-light">
          <button class="delete"></button>
          {% for error in form.non_field_errors %}
            {{ error }}
          {% endfor %}
        </div>
        
      {% endif %}
    
      {% for field in form.visible_fields %}
        <div class="field">
          {{ field.label_tag }}
    
          <div class="control has-icons-right">
          {% if form.is_bound %}
            {% if field.errors %}
              {% render_field field class="input is-danger" %}
              <span class="icon is-small is-right">
                <i class="fas fa-exclamation-triangle"></i>
              </span>
              {% for error in field.errors %}
                <p class="help is-danger">
                  {{ error }}
                </p>
              {% endfor %}
            {% else %}
              {% render_field field class="input is-success" %}
              <span class="icon is-small is-right">
                <i class="fas fa-check"></i>
              </span>
            {% endif %}
          {% else %}
            {% render_field field class="input" %}
          {% endif %}
          </div>
          {% if field.help_text %}
            <small class="help">{{ field.help_text }}</small>
          {% endif %}
        </div>
      {% endfor %}
    
      <div class="field is-grouped">
        <div class="control">
          <button type="submit" class="button is-link">Submit</button>
        </div>
        <div class="control">
          <a href="{% url 'notes:notes' %}" class="button is-link is-light">Cancel</a>
        </div>
      </div>
    </form>
  </div>
</div>



<script>

document.addEventListener('DOMContentLoaded', () => {
  (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
    $notification = $delete.parentNode;

    $delete.addEventListener('click', () => {
      $notification.parentNode.removeChild($notification);
    });
  });
});

</script>

{% endblock content %}

templates/detail.html
{% extends 'base.html' %}

{% block content %}

<div class="columns">
    <div class="column">

        <h1 class="title">{{ note.title }}</h1>
        <p>{{ note.timestamp }}</p>
        
        <div class="content">
            {{note.body}}
        </div>
    </div>
</div>

<div class="level">
    <div class="level-left">
        <div class="level-item">
            <div class="card column">
            <a class="title is-6" href="{% url 'notes:notes' %}">
            <span class="icon has-text-info">
                <i class="fas fa-arrow-left"></i>
            </span>
            Back
            </a>
        </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="columns">
  {% for note in notes %}
  <div class="column is-one-third">
  <div class="card">
      <header class="card-header">
        <p class="card-header-title">
          {{ note.title }}
        </p>
        
      </header>
      <div class="card-content">
        <div class="content">
          {{ note.body|truncatewords_html:15 }}
          <br>
          <time datetime="2016-1-1">{{ note.updated_at|time:"H:i" }} - {{ note.updated_at|date }}</time>
        </div>
      </div>
      <footer class="card-footer">
        <a href="{{ note.get_absolute_url }}" class="card-footer-item">View</a>
        <a href="{% url 'notes:update' note.slug %}" class="card-footer-item">Edit</a>
        <a href="{% url 'notes:delete' note.slug %}" class="card-footer-item">Delete</a>
      </footer>
    </div>
  </div>
  {% empty %}
  <li>No notes</li>
  {% endfor %}

</div>

{% endblock content %}